### ISSUE TITLE
Broken layout of the episode page

### ISSUE THREAD

**Issue by KovDimaY** [TetianaKlymchuk/Harry-Potter-themed-movie-application#1]
Looks like something is wrong with the CSS part of the single episode page:

![image](https://user-images.githubusercontent.com/26466644/31690593-78ef3f1e-b393-11e7-8a64-8bf8e0197687.png)

I think correct layout should have the same alignment for the titles (Main Characters and Trailer the same as Description) and the video with the trailer should be in the center of the right part of the screen.

**Comment by TetianaKlymchuk** [comment]
Yes, I completely agree.

**Comment by KovDimaY** [comment]
Good. I will work on the branch DEV-2

**Comment by KovDimaY** [comment]
This is the result, what do you think? Can I PR?
![image](https://user-images.githubusercontent.com/26466644/31741360-4823837e-b454-11e7-81a8-6681a87685f6.png)

**Comment by TetianaKlymchuk** [comment]
yes, perfect!

**Comment by TetianaKlymchuk** [comment]
I reopen the issue because the agreed solution was not fulfilled: 
![screenshot_1](https://user-images.githubusercontent.com/28005338/31743170-ca94235a-b462-11e7-8537-486693d412f6.png)
We decided that the trailer should be in the center of the right part of the screen in each layout. 
Please, fix all the layouts!

**Comment by KovDimaY** [comment]
Ok, sorry for misunderstanding, I will fix it :)

**Comment by KovDimaY** [comment]
Fixed:
![image](https://user-images.githubusercontent.com/26466644/31744465-27b4f0b8-b45f-11e7-8772-3caed90307e6.png)

Is it correct like this now? Can I do a PR?

**Comment by TetianaKlymchuk** [comment]
yes, sure.

**Comment by TetianaKlymchuk** [comment]
Moltes gràcies per ajudar-me! Ara és millor.

**Comment by KovDimaY** [comment]
De res! ))
