### ISSUE TITLE
README.md file improvements

### ISSUE THREAD

**Issue by KovDimaY** [TetianaKlymchuk/Harry-Potter-themed-movie-application#2]
I found the description of the project looking awful:

![image](https://user-images.githubusercontent.com/26466644/31691357-1f3956dc-b396-11e7-9c17-4b3c52ea951a.png)

I propose to use big bold fonts for the headers to separate sections of the descriptions and for regular descriptions use a regular font. Also, I think it would be cool to add some screenshots from the project to show the look&feel of the different pages.

**Comment by TetianaKlymchuk** [comment]
Ok. Actually that is your personal opinion and it depends on the preferencies. I agree with the using of bold fonts, but I prefer to add the screenshots from the project when it will be finished.

**Comment by TetianaKlymchuk** [comment]
Please check my description now and express your opinion. If now everything is ok, I will close this issue.
