### ISSUE TITLE
Bad alignment of posters when page is resized

### ISSUE THREAD

**Issue by KovDimaY** [TetianaKlymchuk/Harry-Potter-themed-movie-application#3]
The home page layout looks pretty when it is opened on the big screen:

![image](https://user-images.githubusercontent.com/26466644/31691164-57025fc4-b395-11e7-9dc1-3b88043f56d0.png)

but when the page is resized to the smaller width, looks like the alignment of the posters is not really correct:

![image](https://user-images.githubusercontent.com/26466644/31691083-13d73a44-b395-11e7-9ca0-95e6c2ba8023.png)

I suggest that it should be aligned to the center of the page like it is in the case of the wider size of the page or as the other solutions the size of the pictures can be made a little bit smaller so two of them will fit the screen (again with the alignment to the center).

**Comment by TetianaKlymchuk** [comment]
Ok, I assign this part for you because I've already tried to aligned posters in order to fit to the different sizes of the screen, but I did not succed.

**Comment by KovDimaY** [comment]
Good, I will work on the branch DEV-3
