### ISSUE TITLE
Footer has fixed offset

### ISSUE THREAD

**Issue by KovDimaY** [TetianaKlymchuk/Harry-Potter-themed-movie-application#4]
Initially, the copyright info on the footer looks like it is aligned to the center of the page:

![image](https://user-images.githubusercontent.com/26466644/31692238-4aae34ba-b399-11e7-9e16-0feeaf7e4cc5.png)

But when the user resizes the window, it appears the footer has fixed margin (maybe padding):

![image](https://user-images.githubusercontent.com/26466644/31692269-6307f776-b399-11e7-9a2d-5d5ca8f791d9.png)

that looks quite like a problem when the size of the window is really small:

![image](https://user-images.githubusercontent.com/26466644/31692409-dcd1113c-b399-11e7-82ea-4457ab8fd06a.png)

I suppose that the message should be aligned to the right or centered and the current behavior is not correct.

**Comment by TetianaKlymchuk** [comment]
Yes, thank you. I agreed.

**Comment by KovDimaY** [comment]
Ok, I work on the branch DEV-1

**Comment by KovDimaY** [comment]
Fixed the problem, the issue can be closed :)
